databases:
  - name: futari_point_DB
    databaseName: futari_point_db
    user: futari_point
    region: singapore

services:
  - type: web
    name: futari_point
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: futari_point_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

