default: &default
  adapter: postgresql
  encoding: unicode
  username: namerou         # 自分のローカル設定に合わせて
  password: namerou         # 〃
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: futari_point_development

test:
  <<: *default
  database: futari_point_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
  cable:
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
  queue:
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require